global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'default'
    slack_configs:
      - send_resolved: true
        api_url: 'https://hooks.slack.com/services/your_slack_hook'
    telegram_configs:
      - send_resolved: true
        bot_token: 'your_telegram_bot_token'
        chat_id: 'your_chat_id'
